[mongo]
database="server-package"
username="root"
password="12345"
host="mongo"
port=27017

[mqtt]
infoTopic="server-package/info"
errTopic="server-package/error"
username="admin"
password="59524148chenOP"
host="emqx"
cliPrefix="emqx_log_"
port=1883
wsPort=8083
qos=0